import type { Metadata } from "next";
import localFont from "next/font/local";
import "@radix-ui/themes/styles.css";
import "@fnx/ui/styles/globals.css";
// Import Swiper styles
import "swiper/css";
import "./styles/home.styles.css";
import { ThemeProvider } from "next-themes";
import { Theme } from "@radix-ui/themes";
import { ReservationPopUp } from "@/components";
import SessionWrapper from "@/components/auth/session-wrapper";
import { ApolloClientProvider } from "@/components/providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionWrapper>
          <ApolloClientProvider>
            <Theme
              accentColor="purple"
              grayColor="slate"
              appearance="inherit"
              hasBackground={false}
            >
              <ThemeProvider attribute={"class"} defaultTheme="dark">
                <ReservationPopUp />
                {children}
              </ThemeProvider>
            </Theme>
          </ApolloClientProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
