import type { Metadata } from "next";
import localFont from "next/font/local";
import "@radix-ui/themes/styles.css";
import "@fnx/ui/styles/globals.css";
import { ThemeProvider } from "next-themes";
import { Theme } from "@radix-ui/themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme
          accentColor="purple"
          grayColor="slate"
          appearance="inherit"
          hasBackground={false}
        >
          <ThemeProvider attribute={"class"} defaultTheme="light">
         
            {children}
          </ThemeProvider>
        </Theme>
      </body>
    </html>
  );
}
